from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    QUESTION_TYPES = [
        ('MCQ', 'Multiple Choice'),
        ('TF', 'True / False'),
        ('SA', 'Short Answer'),
        ('FIB', 'Fill in the Blanks'),
    ]

    SOURCE_TYPES = [
        ('DB', 'Database'),       # pre-stored by teacher
        ('AI', 'AI Generated'),   # generated by agent
    ]

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='questions')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    question_text = models.TextField()
    question_type = models.CharField(max_length=10, choices=QUESTION_TYPES)
    source = models.CharField(max_length=5, choices=SOURCE_TYPES, default='DB')
    correct_answer = models.TextField()
    explanation = models.TextField(blank=True)   # AI can fill this
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.question_type}] {self.question_text[:60]}"


class Option(models.Model):
    """Only used for MCQ questions"""
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')
    option_text = models.CharField(max_length=300)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.option_text


class QuizSession(models.Model):
    """Tracks when a user generates/requests a set of questions"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sessions')
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    questions = models.ManyToManyField(Question)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.topic} - {self.created_at.date()}"

# Create your models here.
